application:
  autowire:
    commands:
      forced:
        'site:checkout':
          class: \DennisDigital\Drupal\Console\Command\Site\CheckoutCommand
        'site:compose':
          class: \DennisDigital\Drupal\Console\Command\Site\ComposeCommand
        'site:settings:db':
          class: \DennisDigital\Drupal\Console\Command\Site\Settings\DbCommand
        'site:settings:memcache':
          class: \DennisDigital\Drupal\Console\Command\Site\Settings\MemcacheCommand
        'site:settings:local':
          class: \DennisDigital\Drupal\Console\Command\Site\Settings\LocalCommand
        'site:db:import':
          class: \DennisDigital\Drupal\Console\Command\Site\DbImportCommand
        'site:behat:setup':
          class: \DennisDigital\Drupal\Console\Command\Site\BehatSetupCommand
        'site:phpunit:setup':
          class: \DennisDigital\Drupal\Console\Command\Site\PHPUnitSetupCommand
        'site:npm':
          class: \DennisDigital\Drupal\Console\Command\Site\NPMCommand
        'site:grunt':
          class: \DennisDigital\Drupal\Console\Command\Site\GruntCommand
        'site:test:exec':
          class: \DennisDigital\Drupal\Console\Command\Site\TestCommand
        'site:update':
          class: \DennisDigital\Drupal\Console\Command\Site\UpdateCommand
      name: { }
